<?php

namespace Richpolis\PublicacionesBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Richpolis\PublicacionesBundle\Entity\PublicacionGalerias;

/**
 * PublicacionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicacionGaleriasRepository extends EntityRepository
{
    public function findProyectosAndGalerias()
    {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('
            SELECT pg, p, c, g
            FROM PublicacionesBundle:PublicacionGalerias pg
            JOIN pg.galeria c 
            JOIN pg.proyecto p 
            JOIN c.galerias g 
            ORDER BY p.createdAt ASC, g.posicion ASC
        ');
        return $consulta->getResult();
    }
    
    public function findOneProyectoAndGaleria($idProyecto)
    {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('
            SELECT pg, p, c, g
            FROM PublicacionesBundle:PublicacionGalerias pg
            JOIN pg.galeria c 
            JOIN pg.proyecto p 
            JOIN c.galerias g 
            WHERE p.id=:proyecto
            ORDER BY p.createdAt ASC, g.posicion ASC
        ');
        $consulta->setParameter('proyecto', $idProyecto);
        return $consulta->getOneOrNullResult();
    }
}