<?php

namespace Richpolis\FrontendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DiageoUsuariosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiageoUsuariosRepository extends EntityRepository
{
}
